CUDA_VISIBLE_DEVICES=0 python main.py --id baseline --game alien --enable-cudnn --tensorboard-dir ./results/rainbow &
CUDA_VISIBLE_DEVICES=1 python main.py --id baseline --game amidar --enable-cudnn --tensorboard-dir ./results/rainbow &
CUDA_VISIBLE_DEVICES=2 python main.py --id baseline --game assault --enable-cudnn --tensorboard-dir ./results/rainbow &
CUDA_VISIBLE_DEVICES=3 python main.py --id baseline --game asterix --enable-cudnn --tensorboard-dir ./results/rainbow &
CUDA_VISIBLE_DEVICES=0 python main.py --id baseline --game bank_heist --enable-cudnn --tensorboard-dir ./results/rainbow &
CUDA_VISIBLE_DEVICES=1 python main.py --id baseline --game battle_zone --enable-cudnn --tensorboard-dir ./results/rainbow &
CUDA_VISIBLE_DEVICES=2 python main.py --id baseline --game boxing --enable-cudnn --tensorboard-dir ./results/rainbow &
CUDA_VISIBLE_DEVICES=3 python main.py --id baseline --game breakout --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=0 python main.py --id baseline --game chopper_command --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=1 python main.py --id baseline --game crazy_climber --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=2 python main.py --id baseline --game demon_attack --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=3 python main.py --id baseline --game freeway --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=0 python main.py --id baseline --game frostbite --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=1 python main.py --id baseline --game gopher --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=2 python main.py --id baseline --game hero --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=3 python main.py --id baseline --game jamesbond --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=0 python main.py --id baseline --game kangaroo --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=1 python main.py --id baseline --game krull --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=2 python main.py --id baseline --game kung_fu_master --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=3 python main.py --id baseline --game ms_pacman --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=0 python main.py --id baseline --game pong --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=1 python main.py --id baseline --game private_eye --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=2 python main.py --id baseline --game qbert --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=3 python main.py --id baseline --game road_runner --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=0 python main.py --id baseline --game seaquest --enable-cudnn --tensorboard-dir ./results/rainbow &
# CUDA_VISIBLE_DEVICES=1 python main.py --id baseline --game up_n_down --enable-cudnn --tensorboard-dir ./results/rainbow &s