basic:
  device: cuda
  accuracy: float32
  seed: 6666
  verbose: 2

algo:
  num_steps: 5000000
  batch_size: 64
  lr: 0.0003
  memory_size: 300000
  multi_step: 1
  target_entropy_ratio: 0.98
  target_update_interval: 8000
  use_per: False                
  use_dueling: False
  start_steps: 5000
  normalization_steps: 2000
  lamda: 0.97
  clip_reward: False
  zscore_reward: True
  normalize_state: False
  hidden_size: 64
  update_interval: 4
  log_interval: 20
  eval_interval: 10000
  no_term: True
  num_eval_steps: 6000
  gamma: 0.98

env:
  num_parallel_envs: 1
  name: PongNoFrameskip-v4
  state_dtype: uint8
  encoder: CNN